#!/usr/bin/env python3
"""Fetch the papers in docs/RESEARCH.md §10 into papers/ and write papers/INDEX.md.

One file at a time, with a pause and a descriptive User-Agent (RESEARCH §9 pitfall
19). Each PDF is opened with pypdf to check it is a real, readable PDF (not an
HTML error page); its page count and SHA-256 go into papers/INDEX.md. Existing
files are kept (re-checked, not re-downloaded). papers/ is gitignored: most
papers are not licensed for redistribution.

Run on the CT:  pixi run python scripts/fetch_papers.py
"""

from __future__ import annotations

import datetime as dt
import hashlib
import sys
import time
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parents[1]
PAPERS = ROOT / "papers"
UA = "astro-seeing research fetcher/0.1 (personal, non-commercial; one request at a time)"
PAUSE_S = 5.0

# (file name, URL) — RESEARCH.md §10
SOURCES = [
    ("bi2023_remotesensing.pdf", "https://www.mdpi.com/2072-4292/15/9/2225/pdf"),
    ("priyatikanto2026_timau.pdf", "https://arxiv.org/pdf/2604.19023"),
    ("priyatikanto2026_timau.html", "https://arxiv.org/html/2604.19023"),
    ("osborn_sarazin2018.pdf", "https://arxiv.org/pdf/1809.08005"),
    ("haslebacher2022.pdf", "https://arxiv.org/pdf/2208.04918"),
    ("ye2011.pdf", "https://arxiv.org/pdf/1011.3863"),
    ("masciadri2017.pdf", "https://arxiv.org/pdf/1612.00711"),
    ("lascaux2015.pdf", "https://arxiv.org/pdf/1504.01525"),
    ("pierzyna_otclim.pdf", "https://arxiv.org/pdf/2408.00520"),
    ("aksaker2020.pdf", "https://arxiv.org/pdf/1912.01911"),
    ("garcialorenzo2009_teide.pdf", "https://arxiv.org/pdf/0904.0142"),
    ("garcialorenzo2005_v200.pdf", "https://arxiv.org/pdf/astro-ph/0410599"),
    ("tokovinin2003_tololo.pdf", "https://arxiv.org/pdf/astro-ph/0209432"),
    ("schoeck2009_tmt1.pdf", "https://arxiv.org/pdf/0904.1183"),
    ("els2009_tmt6.pdf", "https://arxiv.org/pdf/0904.1865"),
    ("agabi2006_domec.pdf", "https://arxiv.org/pdf/astro-ph/0510418"),
    ("hickson2013_eureka.pdf", "https://arxiv.org/pdf/1305.0615"),
    ("aristidi_pml.pdf", "https://arxiv.org/pdf/2002.04947"),
    (
        "copernicus_dem_handbook.pdf",
        "https://dataspace.copernicus.eu/sites/default/files/media/files/2024-06/"
        "geo1988-copernicusdem-spe-002_producthandbook_i5.0.pdf",
    ),
]
MANUAL = [
    (
        "racine2005.pdf",
        "Racine 2005, PASP 117(830) 401–410, DOI 10.1086/429307 — not on arXiv; add by hand",
    ),
    (
        "garcialorenzo2011_corrigendum.pdf",
        "García-Lorenzo et al. corrigendum, MNRAS 414(2) 801–809,"
        " DOI 10.1111/j.1365-2966.2011.17787.x",
    ),
]


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def check(p: Path) -> str:
    """Return a short description, or raise if the file is not what it should be."""
    if p.suffix == ".pdf":
        from pypdf import PdfReader

        head = p.read_bytes()[:5]
        if head != b"%PDF-":
            raise ValueError(f"not a PDF (starts with {head!r}); probably an error page")
        n = len(PdfReader(str(p)).pages)
        if n < 1:
            raise ValueError("PDF has no pages")
        return f"{n} pages"
    text = p.read_text(errors="replace")
    if "<html" not in text.lower()[:2000]:
        raise ValueError("not HTML")
    return f"{len(text)} chars HTML"


def main() -> int:
    PAPERS.mkdir(exist_ok=True)
    rows, failures = [], []
    s = requests.Session()
    s.headers["User-Agent"] = UA
    for name, url in SOURCES:
        path = PAPERS / name
        if not path.exists():
            print(f"GET {url}", flush=True)
            try:
                r = s.get(url, timeout=120)
                r.raise_for_status()
                tmp = path.with_suffix(path.suffix + ".part")
                tmp.write_bytes(r.content)
                tmp.rename(path)
            except Exception as e:
                failures.append((name, url, str(e)))
                print(f"  FAILED: {e}", flush=True)
                time.sleep(PAUSE_S)
                continue
            time.sleep(PAUSE_S)
        try:
            desc = check(path)
        except Exception as e:
            failures.append((name, url, f"check failed: {e}"))
            print(f"  {name}: CHECK FAILED ({e}); left in place for inspection", flush=True)
            continue
        rows.append((name, url, desc, path.stat().st_size, sha256(path)))
        print(f"  ok {name}: {desc}", flush=True)

    now = dt.datetime.now(dt.UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# papers/INDEX.md",
        "",
        f"Generated by scripts/fetch_papers.py on {now}. Not in git (licences).",
        "",
        "| File | Check | Bytes | SHA-256 | Source |",
        "|---|---|---|---|---|",
    ]
    lines += [f"| {n} | {d} | {b} | `{h}` | {u} |" for n, u, d, b, h in rows]
    lines += ["", "## Failed", ""] + ([f"- {n}: {e} ({u})" for n, u, e in failures] or ["- none"])
    lines += ["", "## Add by hand", ""] + [f"- {n}: {why}" for n, why in MANUAL]
    (PAPERS / "INDEX.md").write_text("\n".join(lines) + "\n")
    print(f"\nwrote {PAPERS / 'INDEX.md'}; {len(rows)} ok, {len(failures)} failed")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
